import requests
import json
from pathlib import Path

parent_dir = Path(__file__).resolve().parent.parent.parent

"""
This imports the data we initally got (some excel sheet) into `./rawSongList.json`.

`lib/songList.json` is autogenerated by scripts/process/convert_raw_english.py. Do not edit songList.json by hand
"""

all_song_url = "https://yted5wtsb0.execute-api.us-east-1.amazonaws.com/dev/googlesheet/1DSDm5bC-BXStA15HJIQqsGKEDZdS9gJ-tyZgIfPYdz4/Sheet1"
res = requests.get(all_song_url)

with open(
    Path.joinpath(parent_dir, "scripts/english_songs/rawSongList.json"), "r"
) as f:
    prev_json = json.loads(f.read())

if prev_json != json.loads(res.text):
    print("json is different")
    with open(
        Path.joinpath(parent_dir, "scripts/english_songs/rawSongList.json"), "w"
    ) as f:
        f.write(res.text)
